server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'web.views.handler404'

urlpatterns = [
    path('', include('web.urls')),
    path('web/api/', include('web.api.urls')),
    path('account/', include('account.urls')),
    path('api/account/', include('account.api.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    # PATIENT VIEW
    path('', views.HomeView.as_view(), name='home'),
    path('patient/', views.PatientRoom.as_view(), name='patient-card'),
    path('patient/card/<int:card_id>/download/', views.DownloadView.as_view(), name='card-download'),
    path('patient/tests/<int:test_id>/', views.AnalyzDetailView.as_view(), name='patient-test'),
    path('patient/appoint/', views.PatientMakeAppoint.as_view(), name='patient-appoint'),

    # DOCTOR VIEW
    path('doctor/', views.DoctorRoomView.as_view(), name='doctor-room'),
    path('doctor/patient_card/<patient_card_id>/', views.DoctorRoomPatientCardView.as_view(), name='doctor-room-pat'),
    path('doctor/patient_card/<patient_card_id>/entry/', views.DoctorPatientEntryView.as_view(), name='doctor-pat-entry'),
    path('doctor/appointments/', views.DoctorAppointments.as_view(), name='doctor-appointments'),

    # CLIENT VIEW
    path('med/about/', views.AboutView.as_view(), name='med-about'),
    path('med/services/', views.ServicesView.as_view(), name='med-services'),
    path('med/departments/', views.DepartmentsView.as_view(), name='med-departments'),
    path('med/departments/<slug:slug>/', views.DepartmentDetailView.as_view(), name='med-department-detail'),
    path('med/doctors/', views.DoctorsListView.as_view(), name='med-doctors'),
    path('med/doctors/<int:dossier_id>/', views.DoctorsDossierDetailView.as_view(), name='med-doctor-detail'),
    path('med/appoint/', views.ClientMakeAppoint.as_view(), name='med-appoint'),
    path('med/appoint/confirmation/', views.AppointConfirmation.as_view(), name='appoint-confirm'),
    path('med/contact/', views.ContactView.as_view(), name='med-contact'),
]

web/models.py
from datetime import timedelta
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django_celery_beat.models import (
    CrontabSchedule, IntervalSchedule,
    PeriodicTask, PeriodicTasks,
)
from .utils import (patient_card_dir_path, patient_card_dir_path_level,
                    limit_patient_choices, limit_note_entry, file_extensions,
                    limit_doctor_choices, limit_doctors_dosier_choices)

User = get_user_model()


class Service(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=250)
    cover = models.ImageField(upload_to='services')

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, blank=True)
    description = RichTextField()
    services_list = models.ManyToManyField(Service, related_name='depart_services', blank=True, default=None)
    cover = models.ImageField(upload_to='departments')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Department, self).save(*args, **kwargs)


class DoctorsDossier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, limit_choices_to=limit_doctor_choices)
    job_position = models.CharField(max_length=255)
    specialization = models.CharField(max_length=255)
    biography = models.JSONField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.email} ({self.job_position})"


class PatientCard(models.Model):  # todo: change to 'PatientFile'
    user = models.OneToOneField(User, on_delete=models.RESTRICT, limit_choices_to=limit_patient_choices)
    created = models.DateTimeField(auto_now_add=True)
    # notes_file = models.FileField(upload_to=patient_card_dir_path,
    #                               validators=[FileExtensionValidator(allowed_extensions=file_extensions())])

    def __str__(self):
        return f"UID: {self.user.pk} - {self.user.get_fullname()} - {self.user.email}"


class PatientNoteEntry(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    patient_card = models.ForeignKey(PatientCard, on_delete=models.CASCADE)
    note = RichTextField(null=True, blank=True)
    made_by = models.ForeignKey(User, on_delete=models.RESTRICT, limit_choices_to=limit_note_entry, default=1) # remove default

    class Meta:
        verbose_name_plural = "Patient Notes"
        verbose_name = 'Patient Note'

    def __str__(self):
        return f"Note for card #{self.patient_card.pk} - {self.patient_card.user.email}"


class PatientAnalysis(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    patient_card = models.ForeignKey(PatientCard, on_delete=models.CASCADE)
    csv_file = models.FileField(upload_to=patient_card_dir_path_level,
                                validators=[FileExtensionValidator(allowed_extensions=file_extensions())])

    class Meta:
        verbose_name_plural = "Patient Analyzes"
        verbose_name = 'Patient Analys'

    def __str__(self):
        return f"Test result for card #{self.patient_card.pk} - {self.patient_card.user.email}"


class CalendarEvent(models.Model):
    STATUSES = (
        ('open', 'open'),
        ('closed', 'closed'),
        ('delay', 'delay'),
        ('processing', 'processing'),
        ('canceled', 'canceled')
    )
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to=limit_doctor_choices, related_name="schedules")
    patient = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to=limit_patient_choices)
    date_time = models.DateTimeField()
    notes = models.TextField(blank=True, null=True, default=None) # todo: remove defaults on production
    status = models.CharField(max_length=20, choices=STATUSES, default='open')

    def __str__(self):
        return f"Event #{self.id} ({self.date_time}) - ({self.status})"


class EventComment(models.Model):
    event = models.ForeignKey(CalendarEvent, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="event_notes",
                               limit_choices_to=limit_note_entry(), null=True)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment to {self.event.date_time}"

templates/web/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- ABOUT PAGE -->

{% include 'web/page_overlay.html' with annot="About us" %}

<section class="section about-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h2 class="title-color">Personal care for your healthy living</h2>
            </div>
            <div class="col-lg-8">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, quod laborum alias. Vitae
                    dolorum, officia sit! Saepe ullam facere at, consequatur incidunt, quae esse, quis ut reprehenderit
                    dignissimos, libero delectus.</p>
                <img src="images/about/sign.png" alt="" class="img-fluid">
            </div>
        </div>
    </div>
</section>

<section class="fetaure-page ">
    <div class="container">
        <div class="row">
            {% for service in services %}
            <div class="col-lg-3 col-md-6">
                <div class="about-block-item mb-5 mb-lg-0">
                    <img src="{{ service.cover.url }}" alt="" class="img-fluid w-100">
                    <h4 class="mt-3">{{ service.name }}</h4>
                    <p>{{ service.description }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="section awards">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4">
                <h2 class="title-color">Our Doctors achievements </h2>
                <div class="divider mt-4 mb-5 mb-lg-0"></div>
            </div>
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="award-img">
                            <img src="images/about/3.png" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="award-img">
                            <img src="images/about/4.png" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="award-img">
                            <img src="images/about/1.png" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="award-img">
                            <img src="images/about/2.png" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="award-img">
                            <img src="images/about/5.png" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="award-img">
                            <img src="images/about/6.png" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section team">
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="section-title text-center">
                    <h2 class="mb-4">Meet Our Specialist</h2>
                    <div class="divider mx-auto my-4"></div>
                    <p>Today’s users expect effortless experiences. Don’t let essential people and processes stay stuck
                        in the past. Speed it up, skip the hassles</p>
                </div>
            </div>
        </div>

        <div class="row">
            {% for doctor in doctors %}
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="team-block mb-5 mb-lg-0">
                    <img src="{{ doctor.photo.url }}" alt="" class="img-fluid w-100">

                    <div class="content">
                        <h4 class="mt-4 mb-0">
                            <a href="{% url 'web:med-doctor-detail' doctor.doctorsdossier.id %}">{{ doctor.get_fullname }}</a>
                        </h4>
                        <p>{{ doctor.doctorsdossier.job_position }}, {{ doctor.doctorsdossier.specialization }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</section>

<section class="section testimonial">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-6">
                <div class="section-title">
                    <h2 class="mb-4">What they say about us</h2>
                    <div class="divider  my-4"></div>
                </div>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-6 testimonial-wrap offset-lg-6">
                <div class="testimonial-block">
                    <div class="client-info ">
                        <h4>Amazing service!</h4>
                        <span>John Partho</span>
                    </div>
                    <p>
                        They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure,
                        ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet
                        nostrum nemo commodi numquam quod.
                    </p>
                    <i class="icofont-quote-right"></i>

                </div>

                <div class="testimonial-block">
                    <div class="client-info">
                        <h4>Expert doctors!</h4>
                        <span>Mullar Sarth</span>
                    </div>
                    <p>
                        They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure,
                        ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet
                        nostrum nemo commodi numquam quod.
                    </p>
                    <i class="icofont-quote-right"></i>
                </div>

                <div class="testimonial-block">
                    <div class="client-info">
                        <h4>Good Support!</h4>
                        <span>Kolis Mullar</span>
                    </div>
                    <p>
                        They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure,
                        ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet
                        nostrum nemo commodi numquam quod.
                    </p>
                    <i class="icofont-quote-right"></i>
                </div>

                <div class="testimonial-block">
                    <div class="client-info">
                        <h4>Nice Environment!</h4>
                        <span>Partho Sarothi</span>
                    </div>
                    <p>
                        They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure,
                        ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet
                        nostrum nemo commodi numquam quod.
                    </p>
                    <i class="icofont-quote-right"></i>
                </div>

                <div class="testimonial-block">
                    <div class="client-info">
                        <h4>Modern Service!</h4>
                        <span>Kolis Mullar</span>
                    </div>
                    <p>
                        They provide great service facilty consectetur adipisicing elit. Itaque rem, praesentium, iure,
                        ipsum magnam deleniti a vel eos adipisci suscipit fugit placeat. Quibusdam laboriosam eveniet
                        nostrum nemo commodi numquam quod.
                    </p>
                    <i class="icofont-quote-right"></i>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/web/analyz_detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <h4>Details of Analyz #{{ analyz.id }} - {{analyz.created}}</h4>
    <div><a href="{% url 'web:patient-card' %}" class="btn-sm btn-primary">back to patient card</a></div>
    {{book | safe}}
</div>

{% endblock %}

templates/web/appointment_confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <section class="section confirmation">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="confirmation-content text-center">
                        <i class="icofont-check-circled text-lg text-color-2"></i>
                        <h2 class="mt-3 mb-4">Thank you for your appoinment</h2>
                        <p>We will contact with you soon.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/web/department_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- DEPARTMENT DETAILS -->

{% include 'web/page_overlay.html' with title="" annot=department.name %}

<section class="section department-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="department-img">
					<img src="{{ department.cover.url }}" alt="" class="img-fluid">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-8">
				<div class="department-content mt-5">
					<h3 class="text-md">{{ department.name }}</h3>
					<div class="divider my-4"></div>
					<p class="lead">{{ department.description | safe }}</p>

					<h3 class="mt-5 mb-4">Services features</h3>
					<div class="divider my-4"></div>
					<ul class="list-unstyled department-service">
						{% for service in department.services_list.all %}
							<li><i class="icofont-check mr-2"></i>{{ service.name }}</li>
						{% endfor %}
					</ul>

					<a href="{% url 'web:med-appoint' %}" class="btn btn-main-2 btn-round-full">Make an Appoinment<i class="icofont-simple-right ml-2  "></i></a>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="sidebar-widget schedule-widget mt-5">
					<h5 class="mb-4">Time Schedule</h5>

					<ul class="list-unstyled">
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Monday - Friday</a>
					    <span>9:00 - 17:00</span>
					  </li>
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Saturday</a>
					    <span>9:00 - 16:00</span>
					  </li>
					  <li class="d-flex justify-content-between align-items-center">
					    <a href="#">Sunday</a>
					    <span>Closed</span>
					  </li>
					</ul>

					<div class="sidebar-contatct-info mt-4">
						<p class="mb-0">Need Urgent Help?</p>
						<h3>+23-4565-65768</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

templates/web/departments.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- DEPARMENTS -->

{% include 'web/page_overlay.html' with title="Departments" annot="Our Department list" %}

<section class="section service-2">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7 text-center">
                <div class="section-title">
                    <h2>Award winning patient care</h2>
                    <div class="divider mx-auto my-4"></div>
                    <p>Lets know moreel necessitatibus dolor asperiores illum possimus sint voluptates incidunt
                        molestias nostrum laudantium. Maiores porro cumque quaerat.</p>
                </div>
            </div>
        </div>

        <div class="row">

            {% for department in departments %}
            <div class="col-lg-4 col-md-6 ">
                <div class="department-block mb-5">
                    <div class="img-cover" style="background: url('{{ department.cover.url }}') 0 0 no-repeat; height: 56vh; background-size: cover;"></div>
                <!--<img src="{{ department.cover.url }}" alt="" class="img-fluid w-100" style="max-height: 230px">-->
                    <div class="content">
                        <h4 class="mt-4 mb-2 title-color">{{ department.name }}</h4>
                        <p class="mb-4">{{ department.description |safe |slice:":61"  }}.</p>
                        <a href="{% url 'web:med-department-detail' department.slug %}" class="read-more">Learn More <i
                                class="icofont-simple-right ml-2"></i></a>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
{% endblock %}

templates/web/doctor_appointments.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-5">
            {% for appoint in appointments %}
            <div class="card mb-3 pt-card {{appoint.status}}">
                <div class="card-body">
                    <h5 class="card-title">{{appoint.date_time}}</h5>
                    <p class="card-text">Patient: {{appoint.patient.get_fullname}}</p>
                    <div class="card-text row">
                        <div class="col-8">
                            Status: <span class="disabled btn-sm btn-info">{{appoint.status}}</span>
                        </div>
                        <div class="col-4">
                            Change to :
                            <select class="form-select CardStatusSelect" aria-label="Status select" data-id="{{appoint.id}}">
                                <option value="none">-----</option>
                                <option value="open">open</option>
                                <option value="closed">closed</option>
                                <option value="delay">delay</option>
                                <option value="processing">processing</option>
                                <option value="canceled">canceled</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="col-5">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">Filter by status</p>
                    <div class="row">
                        <div class="col-8">

                            <select class="form-select" aria-label="Status select" id="statusSelect">
                                <option value="none">-----</option>
                                <option value="open">open</option>
                                <option value="closed">closed</option>
                                <option value="delay">delay</option>
                                <option value="processing">processing</option>
                                <option value="canceled">canceled</option>
                            </select>
                        </div>
                        <div class="col-4">
                            <button class="btn btn-primary" id="statusFilterReset">Show all</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'web/js/appointments.js'%}"></script>
{% endblock %}

templates/web/doctor_room.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <!-- Find Patient's data (card, analyzes etc) DONE -->
    <!-- Read (can't change for now)            DONE -->
    <!-- Create new entry to PT card           -->

    <div class="doctor__patient-list">
        <form method="post" id="ptSearchForm">
            <div class="mb-3 row pt-search">
                {% csrf_token %}
                <label for="doc-pt-search" class="col-sm-2 col-form-label">Patient search</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="doc-pt-search" placeholder="Vanya"/>
                </div>
                <div class="col-sm-2">
                    <input type="submit" value="Search" class="btn btn-outline-primary" id="docPtSearchBtn"/>
                </div>
            </div>
        </form>

        <div class="row">

            <div class="mb-3 pt-found-list col-6">
                <h4 class="">Patient list</h4>
                <div id="ptFoundListId">
                    {% for patient in patient_list %}
                    <div class="card mb-3 doc-pt-card">
                        <div class="card-body">
                            <h5 class="card-title">{{patient.get_fullname}}</h5>
                            <p class="card-text">{{patient.email}}</p>
                            <p class="card-text">{{patient.birth_date}}</p>
                            <p class="card-text">{{patient.phone_number}}</p>
                            <a href="{% url 'web:doctor-room-pat' patient.patientcard.id %}"
                               class="btn btn-sm btn-outline-primary">Open card</a>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>

            <div class="mb-3 pt-found-list col-6" id="doc-appointments-list">
                <h4>Appointments for today : {{appointments|length}}</h4>
                {% for appoint in appointments %}
                <div class="card mb-3 doc-pt-card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{appoint.date_time|date:"SHORT_DATE_FORMAT"}}
                            <span class="text-success">{{ appoint.date_time|time:"H:i" }}</span>
                        </h5>
                        <div class="card-text">Patient: {{appoint.patient.get_fullname}}</div>
                        <div class="card-text">Status: {{appoint.status}}</div>
                    </div>
                </div>
                {% endfor %}
                <hr/>
                <a href="{% url 'web:doctor-appointments' %}" class="btn btn-sm btn-outline-primary">See all
                    appointments</a>

            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'web/js/web.js' %}"></script>
{% endblock %}

templates/web/page_overlay.html
{% load static %}

<section class="page-title bg-1">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block text-center">
                    <span class="text-white">{{ title }}</span>
                    <h1 class="text-capitalize mb-5 text-lg">{{ annot }}</h1>
                </div>
            </div>
        </div>
    </div>
</section>

templates/web/patient_card.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="patient-room-header">
        <div class="row">
            <div class="col-8">
                <h2 class="mb-4"><span class="text-decoration-underline">Patient</span>: {{card.user.get_fullname}}</h2>
            </div>
            <div class="col-4">
                <div id="getBtnRow">
                    <button type="button" class="dwnldRBtn btn btn-outline-primary" id="getCardBtn" data-card="{{card.id}}">
                        <span id="loadSpinner" class="" role="status" aria-hidden="true">&nbsp;</span>
                        Prepare Card
                    </button>
                    {% if request.user.position == 'DR' %}
                    <a href="{% url 'web:doctor-pat-entry' card.id %}" class="dwnldRBtn btn btn-outline-secondary">
                        Make new entry</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-8">
            <div class="patient-card">
                <h4 class="mb-2">Your patient card. All visit data etc.</h4>

                {% for record in card.patientnoteentry_set.all reversed %}
                <div class="card mb-2 patient-card-item">
                    <div class="card-body">
                        <h5 class="card-title">{{record.created}}</h5>
                        <hr/>
                        <div class="card-text">{{record.note | safe}}</div>
                        <p class="card-record disabled"><i>The record was made by: {{record.made_by.get_fullname}}</i></p>
                        <button class="btn btn-primary btn-expand p-2">Expand</button>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-4">
            <div class="patient-tests">
                <h4 class="mb-2">Data about analyzes and tests</h4>

                {% for test in card.patientanalysis_set.all %}
                <div class="card mb-2" style="">
                    <div class="card-body">
                        <h5 class="card-title">{{test.created}}</h5>
                        <hr/>
                        <p class="card-text">{{test.csv_file | safe}}</p>
                        <a href="{% url 'web:patient-test' test.id %}"
                           class="btn-sm btn-primary text-decoration-none">Details</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'web/js/patient_card.js' %}"></script>
{% endblock %}

templates/web/patient_entry_page.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {% for field in form %}
            {% if field.label == "Note" %}
                <div class="row">
                    <div class="col-2">
                        {{ field.label }}
                    </div>
                    <div class="col-10">
                        {{ field }}
                    </div>
                </div>
            {% else %}
                <div class="row" style="display: none;">
                    <div class="col-2">
                        {{ field.label }}
                    </div>
                    <div class="col-10">
                        {{ field }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <div class="col-4">
        <input type="submit" value="Submit" />
        </div>
    </form>
</div>
{% endblock %}

templates/web/services.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- SERVICES PAGE -->

{% include 'web/page_overlay.html' with title="Our services" annot="What We Do" %}

<section class="section service-2">
    <div class="container">
        <div class="row">

            {% for service in services %}
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="service-block mb-5">
                    <img src="{{ service.cover.url }}" alt="" class="img-fluid">
                    <div class="content">
                        <h4 class="mt-4 mb-2 title-color">{{ service.name }}</h4>
                        <p class="mb-4">{{ service.description }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>

<section class="section cta-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="cta-content">
                    <div class="divider mb-4"></div>
                    <h2 class="mb-5 text-lg">We are pleased to offer you the <span class="title-color">chance to have the healthy</span>
                    </h2>
                    <a href="{% url 'web:med-appoint' %}" class="btn btn-main-2 btn-round-full">Get appoinment<i
                            class="icofont-simple-right  ml-2"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}