account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.panel, name='panel'),
    path('update/', views.account_update, name='update'),
    path('signup/', views.signup, name='signup'),
    path('activate/<uidb64>/<token>/', views.activate_user, name='activate'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_change/', views.password_change, name='password_change'),

    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/', views.password_reset_confirm, name="password_reset_confirm"),

]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'web.views.handler404'

urlpatterns = [
    path('', include('web.urls')),
    path('web/api/', include('web.api.urls')),
    path('account/', include('account.urls')),
    path('api/account/', include('account.api.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    # PATIENT VIEW
    path('', views.HomeView.as_view(), name='home'),
    path('patient/', views.PatientRoom.as_view(), name='patient-card'),
    path('patient/card/<int:card_id>/download/', views.DownloadView.as_view(), name='card-download'),
    path('patient/tests/<int:test_id>/', views.AnalyzDetailView.as_view(), name='patient-test'),
    path('patient/appoint/', views.PatientMakeAppoint.as_view(), name='patient-appoint'),

    # DOCTOR VIEW
    path('doctor/', views.DoctorRoomView.as_view(), name='doctor-room'),
    path('doctor/patient_card/<patient_card_id>/', views.DoctorRoomPatientCardView.as_view(), name='doctor-room-pat'),
    path('doctor/patient_card/<patient_card_id>/entry/', views.DoctorPatientEntryView.as_view(), name='doctor-pat-entry'),
    path('doctor/appointments/', views.DoctorAppointments.as_view(), name='doctor-appointments'),

    # CLIENT VIEW
    path('med/about/', views.AboutView.as_view(), name='med-about'),
    path('med/services/', views.ServicesView.as_view(), name='med-services'),
    path('med/departments/', views.DepartmentsView.as_view(), name='med-departments'),
    path('med/departments/<slug:slug>/', views.DepartmentDetailView.as_view(), name='med-department-detail'),
    path('med/doctors/', views.DoctorsListView.as_view(), name='med-doctors'),
    path('med/doctors/<int:dossier_id>/', views.DoctorsDossierDetailView.as_view(), name='med-doctor-detail'),
    path('med/appoint/', views.ClientMakeAppoint.as_view(), name='med-appoint'),
    path('med/appoint/confirmation/', views.AppointConfirmation.as_view(), name='appoint-confirm'),
    path('med/contact/', views.ContactView.as_view(), name='med-contact'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Medical</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'web/img/med_logo_3.png' %}"/>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'web/plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'web/plugins/icofont/icofont.min.css' %}">
    <!-- Slick Slider  CSS -->
    <link rel="stylesheet" href="{% static 'web/plugins/slick-carousel/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'web/plugins/slick-carousel/slick/slick-theme.css' %}">

    <link rel="stylesheet" href="{% static 'web/css/core_styles.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/styles.css' %}">

<!--    &lt;!&ndash; Bootstrap JS CDN &ndash;&gt;-->
<!--    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>-->

</head>
<body>
    {% include 'header.html' %}

    {% if messages %}
    <ul class="messages" style="list-type: none; padding: 0;">
        {% for message in messages %}
        <li role="alert" class="alert alert-primary alert-dismissible fade show {{ message.tags }}">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block body %}
    {% endblock %}

    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
    </script>

    {% include 'footer.html' %}

    <!-- Main jQuery -->
    <script src="{% static 'web/plugins/jquery/jquery.js' %}"></script>
    <!-- Bootstrap 4.3.2 -->
    <script src="{% static 'web/plugins/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'web/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'web/plugins/counterup/jquery.easing.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'web/plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <!-- Counterup -->
    <script src="{% static 'web/plugins/counterup/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'web/plugins/shuffle/shuffle.min.js' %}"></script>
    <script src="{% static 'web/plugins/counterup/jquery.counterup.min.js' %}"></script>

    <script src="{% static 'web/js/script.js' %}"></script>

    {% block scripts %}
    {% endblock %}

</body>
</html>

templates/footer.html
{% load static %}
<!-- footer Start -->
<footer class="footer section gray-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mr-auto col-sm-6">
                <div class="widget mb-5 mb-lg-0">
                    <div class="logo mb-4">
                        <img src="{% static 'web/img/med_logo_3.png' %}" alt="" class="img-fluid" width="50px">
                        <h1 class="col d-inline align-bottom">Medical</h1>
                    </div>
                    <p>Tempora dolorem voluptatum nam vero assumenda voluptate, facilis ad eos obcaecati tenetur
                        veritatis eveniet distinctio possimus.</p>

                    <ul class="list-inline footer-socials mt-4">
                        <li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i
                                class="icofont-facebook"></i></a></li>
                        <li class="list-inline-item"><a href="https://twitter.com/themefisher"><i
                                class="icofont-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i
                                class="icofont-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="widget mb-5 mb-lg-0">
                    <h4 class="text-capitalize mb-3">Department</h4>
                    <div class="divider mb-4"></div>

                    <ul class="list-unstyled footer-menu lh-35">
                        <li><a href="#">Surgery </a></li>
                        <li><a href="#">Wome's Health</a></li>
                        <li><a href="#">Radiology</a></li>
                        <li><a href="#">Cardioc</a></li>
                        <li><a href="#">Medicine</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="widget mb-5 mb-lg-0">
                    <h4 class="text-capitalize mb-3">Support</h4>
                    <div class="divider mb-4"></div>

                    <ul class="list-unstyled footer-menu lh-35">
                        <li><a href="#">Terms & Conditions</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Company Support </a></li>
                        <li><a href="#">FAQuestions</a></li>
                        <li><a href="#">Company Licence</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="widget widget-contact mb-5 mb-lg-0">
                    <h4 class="text-capitalize mb-3">Get in Touch</h4>
                    <div class="divider mb-4"></div>

                    <div class="footer-contact-block mb-4">
                        <div class="icon d-flex align-items-center">
                            <i class="icofont-email mr-3"></i>
                            <span class="h6 mb-0">Support Available for 24/7</span>
                        </div>
                        <h4 class="mt-2"><a href="tel:+23-345-67890">Support@email.com</a></h4>
                    </div>

                    <div class="footer-contact-block">
                        <div class="icon d-flex align-items-center">
                            <i class="icofont-support mr-3"></i>
                            <span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
                        </div>
                        <h4 class="mt-2"><a href="tel:+23-345-67890">+23-456-6588</a></h4>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-btm py-4 mt-5">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-6">
                    <div class="copyright">
                        &copy; Copyright Reserved to <span class="text-color">Novena</span> by <a
                            href="https://themefisher.com/" target="_blank">Themefisher</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="subscribe-form text-lg-right mt-5 mt-lg-0">
                        <form action="#" class="subscribe">
                            <input type="text" class="form-control" placeholder="Your Email address">
                            <a href="#" class="btn btn-main-2 btn-round-full">Subscribe</a>
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <a class="backtop js-scroll-trigger" href="#top">
                        <i class="icofont-long-arrow-up"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
<header>
    <div class="header-top-bar">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <ul class="top-bar-info list-inline-item pl-0 mb-0">
                        <li class="list-inline-item"><a href="mailto:support@gmail.com"><i
                                class="icofont-support-faq mr-2"></i>support@novena.com</a></li>
                        <li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>Address Ta-134/A, New
                            York, USA
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <div class="text-lg-right top-right-bar mt-2 mt-lg-0">
                        <a href="tel:+23-345-67890">
                            <span>Call Now : </span>
                            <span class="h4">823-4565-13456</span>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3">
                    {% if request.user.is_authenticated %}
                    <a class="btn btn-light float-right" href="{% url 'account:panel' %}">
                        <i class="bi bi-person-circle"></i>
                        Dashboard
                    </a>
                    {% else %}
                    <a class="btn btn-light float-right" href="{% url 'account:login' %}">
                        <i class="bi bi-door-open-fill"></i>
                        Login
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navigation" id="navbar">
        <div class="container">
            <div class="row">
                <a class="navbar-brand col my-0 me-2 p-0 d-block" href="{% url 'web:home' %}">
                    <img src="{% static 'web/img/med_logo_3.png' %}" alt="" class="img-fluid d-inline" width="40px">
                    <h1 class="col d-inline align-bottom">Medical</h1>
                </a>
            </div>

            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain"
                    aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
                <span class="icofont-navigation-menu"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarmain">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'web:home' %}">Home</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'web:med-about' %}">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'web:med-services' %}">Services</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'web:med-departments' %}" id="dropdown02">Departments</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Doctors <i class="icofont-thin-down"></i></a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown03">
                            <li><a class="dropdown-item" href="{% url 'web:med-doctors' %}">Doctors</a></li>
                            {% if request.user.is_authenticated and request.user.position == 'PT' %}
                            <li><a class="dropdown-item" href="{% url 'web:patient-appoint' %}">Appoinment</a></li>
                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'web:med-appoint' %}">Appoinment</a></li>
                            {% endif %}
                        </ul>
                    </li>

<!--                    <li class="nav-item dropdown">-->
<!--                        <a class="nav-link dropdown-toggle" href="blog-sidebar.html" id="dropdown05"-->
<!--                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Blog <i-->
<!--                                class="icofont-thin-down"></i></a>-->
<!--                        <ul class="dropdown-menu" aria-labelledby="dropdown05">-->
<!--                            <li><a class="dropdown-item" href="">Blog with Sidebar</a></li>-->

<!--                            <li><a class="dropdown-item" href="">Blog Single</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
                    <li class="nav-item"><a class="nav-link" href="{% url 'web:med-contact' %}">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>